### ISSUE TITLE
'more than one entry matches that name and claimID' error

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#246]
from spee.ch logs
Request Error: /bb8cd8dbcdc5c7ae59847f71489575c3f9249dd5/3805744870065513168311637839002n
```stack: 'Error: more than one entry matches that name and claimID\n    at db.sequelize.query.then.result (/home/lbry/spee.ch/models/index.js:246:19)\n    at tryCatcher (/home/lbry/spee.ch/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/lbry/spee.ch/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/lbry/spee.ch/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/lbry/spee.ch/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/lbry/spee.ch/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/home/lbry/spee.ch/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/lbry/spee.ch/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/lbry/spee.ch/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)' ```
``` message: 'more than one entry matches that name and claimID' ```

**Comment by billbitt** [comment]
somehow the sync tool put two entries for this claim into the production db.  However, this was not the case on staging.
