### ISSUE TITLE
'claimid not found in possible sorted list' error

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#247]
from spee.ch logs:
Request Error: /@Zeb:15d6c0ba195a60d47a0916a560c2d98d570c53ee
stack: 
``` 'Error: claimid not found in possible sorted list\n    at sortResult (/home/lbry/spee.ch/models/index.js:35:31)\n    at db.sequelize.query.then.result (/home/lbry/spee.ch/models/index.js:208:28)\n    at tryCatcher (/home/lbry/spee.ch/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/lbry/spee.ch/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/lbry/spee.ch/node_modules/bluebird/js/release/promise.js:569:18)\n Show more… ```
message: 
``` 'claimid not found in possible sorted list' ```

**Comment by billbitt** [comment]
error no longer happening
