### ISSUE TITLE
res.sendFile not receiving a path argument

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#437]
```
Error on /Ichigo.Chocola.Flavor
stack: 'TypeError: path argument is required to res.sendFile\n    at ServerResponse.sendFile (/home/lbry/www.spee.ch/node_modules/express/lib/response.js:411:11)\n    at serveFile (/home/lbry/www.spee.ch/node_modules/spee.ch/server/controllers/assets/utils/serveFile.js:11:19)\n    at getClaimId.then.then.then.fileRecord (/home/lbry/www.spee.ch/node_modules/spee.ch/server/controllers/assets/utils/getClaimIdAndServeAsset.js:26:7)'
message: 'path argument is required to res.sendFile'
```
It is happening very rarely, but I noticed this error in #speech.  It looks like somehow `sendFile` is not receiving a filepath sometimes.  Only saw this with this route.

**Comment by billbitt** [comment]
Another instance of this happening:
```
Error on /@lbryteam:6/mike-vine.jpg
stack: 'TypeError: path argument is required to res.sendFile\n    at ServerResponse.sendFile (/home/lbry/www.spee.ch/node_modules/express/lib/response.js:411:11)\n    at serveFile (/home/lbry/www.spee.ch/node_modules/spee.ch/server/controllers/assets/utils/serveFile.js:11:19)\n    at getClaimId.then.then.then.fileRecord (/home/lbry/www.spee.ch/node_modules/spee.ch/server/controllers/assets/utils/getClaimIdAndServeAsset.js:26:7)'
message: 'path argument is required to res.sendFile'
```

**Comment by tzarebczan** [comment]
Related from #spee.ch-info...still not sure how these are happening. 
http://spee.ch/1eefcc51f95969a458f2a080593c813bd1ab1732/IMG20180118161246.jpeg
```

no fileType provided for undefined
Error on /1eefcc51f95969a458f2a080593c813bd1ab1732/IMG20180118161246.jpeg
stack: 'TypeError: path argument is required to res.sendFile\n    at ServerResponse.sendFile (/home/lbry/www.spee.ch/node_modules/express/lib/response.js:411:11)\n    at serveFile (/home/lbry/www.spee.ch/node_modules/spee.ch/server/controllers/assets/utils/serveFile.js:14:19)\n    at getClaimId.then.then.then.then.fileRecord (/home/lbry/www.spee.ch/node_modules/spee.ch/server/controllers/assets/utils/getClaimIdAndServeAsset.js:31:7)\n    at <anonymous>'
message: 'path argument is required to res.sendFile'
```

**Comment by alyssaoc** [comment]
closing, reopen if you find it again
