### ISSUE TITLE
Clicking play button on twitter spee.ch hyperlink goes to invalid page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#597]
When I clicked the play button on https://twitter.com/jsigwart/status/1039963212358266880?s=19 , I see an error page on this url https://spee.ch/video-embed/tom-juggling/1d61d90d3c2ad28d705802e00712b190e7b25732

Clicking the view on spee.ch button works. 

```
Error: Failed to lookup view "embed" in views directory "/home/lbry/spee.ch/node_modules/spee.ch/server/views"
    at Function.render (/home/lbry/spee.ch/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/home/lbry/spee.ch/node_modules/express/lib/response.js:1008:7)
    at sendVideoEmbedPage (/home/lbry/spee.ch/server/controllers/pages/sendVideoEmbedPage.js:10:19)
    at Layer.handle [as handle_request] (/home/lbry/spee.ch/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/lbry/spee.ch/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/lbry/spee.ch/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/lbry/spee.ch/node_modules/express/lib/router/layer.js:95:5)
    at /home/lbry/spee.ch/node_modules/express/lib/router/index.js:281:22
    at param (/home/lbry/spee.ch/node_modules/express/lib/router/index.js:354:14)
    at param (/home/lbry/spee.ch/node_modules/express/lib/router/index.js:365:14)
    at param (/home/lbry/spee.ch/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/lbry/spee.ch/node_modules/express/lib/router/index.js:410:3)
    at next (/home/lbry/spee.ch/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/home/lbry/spee.ch/node_modules/passport/lib/middleware/authenticate.js:338:9)
    at SessionStrategy.authenticate (/home/lbry/spee.ch/node_modules/passport/lib/strategies/session.js:75:10)
    at attempt (/home/lbry/spee.ch/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/home/lbry/spee.ch/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/home/lbry/spee.ch/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/lbry/spee.ch/node_modules/express/lib/router/index
```

**Comment by skhameneh** [comment]
Note: The `twitter:player` meta tag for this Spee.ch content is producing the URL @tzarebczan provided.

**Comment by skhameneh** [comment]
Public users seeing the raw trace relates to: https://github.com/lbryio/spee.ch/issues/582
