### ISSUE TITLE
Undefined updatedAt results in timeout

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#921]
https://spee.ch/fuckfairness is not loading for me and returns a 524 from Cloudflare. The following was available in #speech-errors:

```
'TypeError: Cannot read property \'updatedAt\' of null\n    at /home/lbry/spee.ch/server/bundle/server.js:1:551337\n    at tryCatch (/home/lbry/spee.ch/node_modules/regenerator-runtime/runtime.js:62:40)\n    at Generator.invoke [as _invoke] (/home/lbry/spee.ch/node_modules/regenerator-runtime/runtime.js:296:22)\n    at Generator.prototype.(anonymous function) [as next] (/home/lbry/spee.ch/node_modules/regenerator-runtime/runtime.js:114:21)\n    at a (/home/lbry/spee.ch/server/bundle/server.js:1:550584)\n    at s (/home/lbry/spee.ch/server/bundle/server.js:1:551512)\n    at <anonymous>'
```

**Comment by tzarebczan** [comment]
https://spee.ch/FuckFairness does work - so it may be related to case?
